# _config.yml
# Site settings
title: Pangalactic Post
description: News from the End of the Universe
baseurl: ""
url: "https://greaselovely.github.io"

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title:output_ext

# Other settings
lsi: false
safe: true
incremental: false
highlighter: rouge

gist:
  noscript: false

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings