lsi: false
safe: true
source: greaselovely.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme
title: Snark Byte
description: Unfiltered Nerdery