# _config.yml
title: Pangalactic Post
description: News from the End of the Universe
baseurl: ""
url: "https://greaselovely.github.io"

markdown: kramdown
kramdown:
   input: GFM
   hard_wrap: true
permalink: /blog/:year/:month/:day/:title:output_ext

plugins:
  - jekyll-feed